//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infodinamica.Framework.Exportable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infodinamica.Framework.Exportable.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor &quot;{0}&quot; no puede ser convertido a un número válido.
        /// </summary>
        public static string CannotParseNumber {
            get {
                return ResourceManager.GetString("CannotParseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han presentado {0} errores al validar los datos antes de exportarlos. Para más informacion, revise la propiedad &quot;Data&quot;.
        /// </summary>
        public static string EngineHasBusinessExceptions {
            get {
                return ResourceManager.GetString("EngineHasBusinessExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versión especificada para crear el archivo Excel (XLS o XLSX) es inválida.
        /// </summary>
        public static string Excel_BadVersion {
            get {
                return ResourceManager.GetString("Excel_BadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha proporcionado la extensión del archivo.
        /// </summary>
        public static string FileExtensionNotProvided {
            get {
                return ResourceManager.GetString("FileExtensionNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extensión {0} proporcionada para exportar el archivo es inválida.
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La llave {0} no existe.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen posiciones repetidas en la hoja {0}. Revise el atributo &quot;ExportableAttribute&quot;.
        /// </summary>
        public static string RepeatedPosition {
            get {
                return ResourceManager.GetString("RepeatedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se proporcionó el nombre de la hoja a importar.
        /// </summary>
        public static string SheetNameNotProvided {
            get {
                return ResourceManager.GetString("SheetNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado la hoja {0}.
        /// </summary>
        public static string SheetNotFound {
            get {
                return ResourceManager.GetString("SheetNotFound", resourceCulture);
            }
        }
    }
}
